name: ASP.NET Core Build and Deploy # Name of the GitHub workflow

on:
  push:
    branches:
      - main # Trigger the workflow when code is pushed to the 'main' branch

jobs:
  build: # Define the 'build' job
    runs-on: ubuntu-latest # Use the latest version of Ubuntu as the runner
    steps:
    - name: Checkout code # Step to checkout the repository's code
      uses: actions/checkout@v2 # Use the checkout action to retrieve the code

    - name: Setup .NET # Step to set up the .NET environment
      uses: actions/setup-dotnet@v3 # Use the setup-dotnet action
      with:
        dotnet-version: '8.0.x' # Specify the .NET version to use (updated to .NET 8)

    - name: Restore dependencies # Step to restore project dependencies
      run: dotnet restore # Command to restore the dependencies

    - name: Build # Step to build the project
      run: dotnet build --configuration Release --no-restore # Command to build the project in Release configuration

    - name: Test # Step to run tests
      run: dotnet test --no-restore --verbosity normal # Command to run tests

    - name: Publish
      run: dotnet publish --output out

    - name: Upload build artifact # Step to upload the build artifact 
      uses: actions/upload-artifact@v3 
      with: 
        name: build-artifact 
        path: ${{github.workspace}}/out/** # Specify the path to the artifact

  deploy: # Define the 'deploy' job
    runs-on: ubuntu-latest # Use the latest version of Ubuntu as the runner
    needs: build # Specify that the 'deploy' job depends on the 'build' job

    steps:
    - name: Download build artifact # Step to download the build artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact
        path: ${{github.workspace}}/out # Specify the path to download the artifact

    - name: Login to Azure # Step to login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # Use the Azure credentials stored in GitHub secrets

    - name: Deploy to Azure Web App # Step to deploy the application to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ vars.WEBAPP_NAME }} # Specify the name of the Azure Web App
        package: ${{ github.workspace }}/out # Specify the path to the build artifact
        slot-name: 'production' # Specify the deployment slot name
